### ISSUE TITLE
Lime Scooters not showing on map

### ISSUE THREAD

**Issue by davidwim** [finncodes/openscootermap#14]
Lime scooters are not showing up on the map and when I run the Request URL, it comes up with a 403 error.
![Screen Shot 2020-08-14 at 6 02 38 PM](https://user-images.githubusercontent.com/63693881/90218798-cd3c7080-de58-11ea-8326-71254ed5134b.png)

**Comment by finncodes** [comment]
I was about to reply on the other issue thread about that - would you be able to paste the cURL for the ScooterMap endpoint that gets the auth token for Lime? I'm still having issues even on Chrome with adblockers disabled.

**Comment by davidwim** [comment]
Sure - 
```
curl 'https://web-production.lime.bike/api/rider/v1/views/map?ne_lat=<N_E_LATITUDE>&ne_lng=<N_E_LONGITUDE>&sw_lat=<S_W_LATITUDE>&sw_lng=<S_W_LONGITUDE>&user_latitude=USER_LATITUDE&user_longitude=USER_LONGITUDE&zoom=18' \
  -H 'Accept-Language: en-US' \
  -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX3Rva2VuIjoiUFNFQUxQNFQ0WVlaWCIsImxvZ2luX2NvdW50IjoxfQ.IwZCyO423W_YrtXLR3W9JGtsWIvH-2BcnCiCWj-mrKI' \
  -H 'X-Device-Token: 9e8223cb-b88e-45a0-8da9-7a82dee87650' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Referer: https://scootermap.com/map' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36' \
  -H 'Mobile-Registration-Id: ef3VWXptnVI:APA91bHUSogqj_qHPZhzDmK-dRv_mZaku2z92w96tGbVjkIzzpTyDHgz1oW2IH0sHEF0mffluRnAlwQkLDR3wJax3fR83aDvw88Rx8kNWIdPDmAjURHBQLelBQkCnLnDcAWT4gjZM3pT' \
  -H 'X-Session-ID: 1528741779878' \
  -H 'App-Version: 2.66.3' \
  --compressed```

**Comment by finncodes** [comment]
I found the endpoint to get the auth code for Lime - it's at `https://scootermap.com/api/lime/auth-code`. A request is made to this first to get the value for the authorisation header - it probably changes on a regular basis and so I can use it to fix the 403.

**Comment by davidwim** [comment]
I've noticed that the Scooter Map Auth header has never changed, but the one on my personal Lime account has a few times. I've been using the same one for a few months now.
