### ISSUE TITLE
Find Beam scooter API endpoints

### ISSUE THREAD

**Issue by finncodes** [finncodes/openscootermap#2]
Beam (https://www.ridebeam.com/) is a scooter sharing company serving the Asia-Pacific region and we are looking for someone to help us by reverse engineering their mobile app or proxying requests through packet capture.

Hopefully the endpoints and the required request format needed to load their scooter locations can be found this way, and then we will be able to add them to the map.

**Comment by drdrjojo** [comment]
I'll take this
