### ISSUE TITLE
Find Uber scooter API endpoints

### ISSUE THREAD

**Issue by finncodes** [finncodes/openscootermap#3]
Uber provides scooter sharing through the brand Jump (https://nz.jump.com/nz/en/) and we are looking for someone to help us by reverse engineering their mobile app or proxying requests through packet capture.

Unfortunately the endpoints documented in the WoBike repository (https://github.com/ubahnverleih/WoBike#jump-usa) do not provide the locations of scooters. 

Hopefully the endpoints and the required request format needed to load their scooter locations can be found this way, and then we will be able to add them to the map.

**Comment by zjael** [comment]
I will give it a shot. :)

**Comment by finncodes** [comment]
Bike endpoints have been added, we are now just looking for someone to help find the scooter endpoints from the Uber app

**Comment by jesserockz** [comment]
https://github.com/NABSA/gbfs/blob/master/systems.csv

**Comment by finncodes** [comment]
@jesserockz I took a look through that CSV and couldn't find anything for the Uber Jump scooters here. I tried emailing Uber Engineering a few months ago to find out if they have any GBFS URLs for Jump here in New Zealand but I unfortunately I didn't receive a response. As far as I know the only way to find the scooter locations would be to proxy/MITM the app - however I believe certificate pinning on recent iOS and Android versions makes it a bit complicated.

**Comment by jesserockz** [comment]
Yeah, it looks like most of the other cities have been found by guessing maybe.
`https://gbfs.uber.com/v1/laxs/gbfs.json` - Los Angeles

2/3/4 letter city/airport code followed by `s` for scooter or `b` for bike.
Tried a few combinations for Wellington but have not gotten it yet.

**Comment by davidwim** [comment]
JUMP Scooters and Bikes can now be found under the Lime's API as `"brand": "jump"`.
