### ISSUE TITLE
New Vehicle Icons

### ISSUE THREAD

**Issue by davidwim** [finncodes/openscootermap#9]
I've found vehicle icons from Beam and Lime

**Lime**

High Bat: 
![image](https://user-images.githubusercontent.com/63693881/87393749-bbba3b80-c602-11ea-8fcd-b7eab4a0d67d.png)

Medium Bat:
![image](https://user-images.githubusercontent.com/63693881/87393799-cffe3880-c602-11ea-8955-60aee1006802.png)

Low Bat:
![image](https://user-images.githubusercontent.com/63693881/87393836-df7d8180-c602-11ea-8fc5-94b23bc3d912.png)

Standard:
![image](https://user-images.githubusercontent.com/63693881/87393906-fd4ae680-c602-11ea-8dd9-989c7108211a.png)

**Beam**

High Bat:
![image](https://user-images.githubusercontent.com/63693881/87394096-5c106000-c603-11ea-880d-6fccd6cfdc8f.png)

Medium Bat:
![image](https://user-images.githubusercontent.com/63693881/87394133-69c5e580-c603-11ea-959a-c7136cf352d8.png)

Low Bat:
![image](https://user-images.githubusercontent.com/63693881/87394153-721e2080-c603-11ea-9eef-326e1a5e7ee5.png)

High Bat Gift:
![image](https://user-images.githubusercontent.com/63693881/87394514-fffa0b80-c603-11ea-9a72-f3a1687eff86.png)

Medium Bat Gift:
![image](https://user-images.githubusercontent.com/63693881/87394548-09837380-c604-11ea-8701-269735f88f68.png)

Low Bat Gift:
![image](https://user-images.githubusercontent.com/63693881/87394581-11431800-c604-11ea-924e-fb7eceaf3609.png)

**Comment by finncodes** [comment]
Awesome - do you have any ideas on what the Beam gift ones could be used for?

**Comment by davidwim** [comment]
If you take a look at my previous issue about Beam and look at the official app screenshot, there are some that have those gift icons. They are an incentive that gives the user $0.50 to $1 of credit to unlock. It's included in the API data so it shouldn't be that hard to intergrate.

Here's the data from the API on a Gift Scooter:
```
"omniIotImei": "868020030548241",
                "Tasks": [
                    {
                        "id": 1694195,
                        "name": "Inactive",
                        "queryName": "INACTIVE",
                        "description": "Get $0.75 back when you end at a parking spot!",
                        "priority": 4,
                        "expiryDateTime": "2020-07-15T09:11:13.813Z",
                        "vehicleId": 5015,
                        "assigneeId": null,
                        "userMode": 0,
                        "startCriteria": "START_TRIP",
                        "completionCriteria": null,
                        "rewardsUponStarting": "0.750",
                        "rewardsUponCompleting": null,
                        "rewardsEarned": "0.000",
                        "reason": null,
                        "status": 0,
                        "createdAt": "2020-07-13T07:11:13.816Z",
                        "updatedAt": "2020-07-13T07:11:13.816Z",
                        "startedAt": null,
                        "completedAt": null,
                        "completedBy": null,
                        "startCriteriaParameters": null,
                        "completionCriteriaParameters": null
                    }
                ],
                "formFactor": "escooter"
            }
```
